"""add type to messages

Revision ID: 6ba2b943f04b
Revises: ed67559ffceb
Create Date: 2026-07-02 11:29:05.740196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba2b943f04b'
down_revision: Union[str, None] = 'ed67559ffceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ajouter la colonne avec une valeur par défaut pour les messages existants
    op.add_column('messages', sa.Column('type', sa.String(length=20), nullable=False, server_default='transactional'))
    # Retirer le server_default après la migration
    op.alter_column('messages', 'type', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
